services:
  php:
    build:
      context: .
      target: frankenphp_dev
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      - ./frankenphp/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro
    environment:
      APP_ENV: dev
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"

  database:
    ports:
      - target: 3306
        published: ${MYSQL_PORT:-3306}
